- defaults:
    brewfile:
      force_intel: true
      auto_bootstrap: false
      stdin: true
      stdout: true
      stderr: true
- brewfile:
  - brewfiles/mac/personal/Brewfile
  - brewfiles/mac/personal/Brewfile_mas
