- shell:
    - description: install homebrew
      command: '[[ $(command -v brew) != "" ]] || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      stdout: true
      stdin: true
