- shell:
  - '( [[ ! -d ~/docker/nodered ]] && mkdir -p ~/docker/nodered && sudo chown -R dockremap:$USER ~/docker/nodered && sudo chmod -R 775 ~/docker/nodered) || true'
  - 'docker-compose -f ~/.dotfiles/docker/nodered/docker-compose.yml up -d'
  - 'docker exec nodered sh -c "cd /data && npm install node-red-contrib-smartthings"'
  - 'docker exec nodered sh -c "cd /data && npm install node-red-contrib-dyson-purelink"'
