- shell:  
  - command:  '[[ $(docker volume ls | grep portainer_data) ]] || ( docker volume create portainer_data)'
    quiet: false
    stdin: true
    stdout: true
    stderr: true
  - command:  '[[ $(docker ps | grep portainer) ]] || docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data --restart always portainer/portainer'
    quiet: false
    stdin: true
    stdout: true
    stderr: true
