- shell:
  - sudo mkdir -p ~/docker/pihole/var/log
  - sudo touch ~/docker/pihole/var/log/pihole.log
  - command:  'docker-compose -f ~/.dotfiles/docker/pihole/docker-compose.yml up -d'
    quiet: false
    stdin: true
    stdout: true
    stderr: true
