- defaults:
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true
- shell:
  - '( [[ ! -d ~/docker/assistant_relay ]] && mkdir -p ~/docker/assistant_relay && sudo chown -R dockremap:$USER ~/docker/assistant_relay && sudo chmod -R 775 ~/docker/assistant_relay) || true'
  - 'docker-compose -f docker/assistant_relay/docker-compose.yml up -d'
