- shell:
  - mkdir -p ~/.dotfiles/pihole-data
  - chown dockremap:miguely ~/.dotfiles/pihole-data
  - command:  'docker-compose -f ~/.dotfiles/docker/pihole/docker-compose.yml up -d'
    quiet: false
    stdin: true
    stdout: true
    stderr: true
