- shell:
  - 'DIR=~/docker/homebridge; ( [[ ! -d $DIR ]] && mkdir -p $DIR && sudo chown -R dockremap:$USER $DIR && sudo chmod -R 775 $DIR) || true'
  - command:  'docker-compose -f ~/.dotfiles/docker/homebridge/docker-compose.yml up -d'
    stdin: true
    stdout: true
    stderr: true
  - 'docker exec homebridge npm uninstall homebridge-dummy'
  - 'docker exec homebridge npm install homebridge-smartthings-v2'
