- apt:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

- shell:
  - command: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
    stdin: true
    stdout: true
    quiet: false
  - command: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
    stdin: true
    stdout: true
    quiet: false
  - command: 'sudo apt-get update'
    stdin: true
    stdout: true
    quiet: false
- apt:
  - docker-ce
  - docker-ce-cli
  - containerd.io
