- shell:
  - 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - '
  - 'sudo sh -c ''echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'''
  - 'sh -c ''mkdir -p /tmp/theme/ && cd /tmp/theme && git clone git@github.com:vinceliuice/Yosemite-gtk-theme.git && cd Yosemite-gtk-theme && ./Install'' || true'
  - 'sh -c ''mkdir -p ~/.icons && cd ~/.icons && git clone https://github.com/keeferrourke/la-capitaine-icon-theme.git && cd la-capitaine-icon-theme && ./configure'' || true'
  - 'mkdir -p ~/.local/share/fonts'
  - 'sh -c ''cd ~/.local/share/fonts && curl -fLo "Meslo LG M Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf'' || true'
- apt:
  - gnome-tweak-tool
  - google-chrome-stable
  - gtk2-engines-murrine
  - gtk2-engines-pixbuf
  - libglib2.0-dev-bin
  - libxml2-utils
- snap:
  - discord
  - obs-studio
  - spotify
  - vlc
- snap-classic:
  - code
  - slack
