- defaults:
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true

- shell:
  - 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - '
  - 'sudo sh -c ''echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'''
  - 'mkdir -p ~/.local/share/fonts'
  - 'sh -c ''cd ~/.local/share/fonts && curl -fLo "Meslo LG M Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf'' || true'
- apt:
  - chrome-gnome-shell
  - cinnamon
  - gnome-shell-extensions
  - gnome-tweak-tool
  - google-chrome-stable
  - gtk2-engines-murrine
  - gtk2-engines-pixbuf
  - libglib2.0-dev-bin
  - libxml2-utils
- snap:
  - discord
  - obs-studio
  - vlc
- snap-classic:
  - code
  - slack
