- defaults:
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true

- shell:
  - '[[ $(command -v brew) != "" ]] || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'
- brewfile:
  - brewfiles/mac/basics/Brewfile
