- shell:
  - description: Creating SSH key for github
    command: '[[ -a ~/.ssh/id_rsa ]] || ssh-keygen -t rsa -b 4096 -C "miguelandres@users.noreply.github.com"'
    stdout: true
    stdin: true
  - description: Starting the SSH agent, check there is a PID below.
    command: 'eval "$(ssh-agent -s)"'
    stdout: true
    stdin: true
  - description: Adding private key to SSH agent
    command: 'ssh-add ~/.ssh/id_rsa'
  - description: 'Copy the SSH key into https://github.com/settings/keys. Already in the clipboard.'
    command: 'pbcopy < ~/.ssh/id_rsa.pub'
- link:
    ~/.ssh/config: 
      force: true
      path: ssh/mac-config-corp
