- defaults:
    installBrew:
      force_intel: false
      stdin: true
      stdout: true
      stderr: true
    brewfile:
      force_intel: false
      auto_bootstrap: false
      stdin: true
      stdout: true
      stderr: true
    link:
      create: true
      relink: true
- installBrew:
    - brew
    - cask
- shell:
    - echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    - source ~/.zprofile
- link:
    ~/Library/LaunchAgents/sh.brew.update.plist: mac/sh.brew.update.plist
    ~/Library/LaunchAgents/sh.brew.upgrade.plist: mac/sh.brew.upgrade.plist
- shell:
    - cp -Rf ~/.dotfiles/mac/Workflows/Services/* ~/Library/Services
    - launchctl load /Users/$USER/Library/LaunchAgents/sh.brew.update.plist
    - launchctl load /Users/$USER/Library/LaunchAgents/sh.brew.upgrade.plist
- brewfile:
    - brewfiles/mac/basics/Brewfile
