- defaults:
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true

- shell:
  - '[[ $(command -v brew) != "" ]] || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
- brewfile:
  - brewfiles/mac/basics/Brewfile
