- defaults:
    brewfile:
      force_intel: true
      auto_bootstrap: false
      stdin: true
      stdout: true
      stderr: true
- brewfile:
    - brewfiles/mac/basics/Brewfile_mas
- shell:
    - cp -Rf ~/.dotfiles/mac/Workflows/Services/* ~/Library/Services
