- defaults:
    installBrew:
      force_intel: true
      stdin: true
      stdout: true
      stderr: true
    brewfile:
      force_intel: true
      auto_bootstrap: false
      stdin: true
      stdout: true
      stderr: true
- installBrew:
  - brew
  - cask
- brewfile:
  - brewfiles/mac/basics/Brewfile
