- link:
    ~/.mackup.cfg:
      force: true
      path: mackup/mackup.cfg
- shell:
    - mackup restore
    - cd ~/Google\ Drive/Mackup/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin; chmod +x *
    - mackup backup
