- link:
    ~/.mackup.cfg:
      force: true
      path: mackup/mackup.cfg
- shell:
    - command: mackup restore
      stdin: true
      stdout: true
    - command: cd ~/Google\ Drive/Mackup/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin; chmod +x *
      description: Fix permissions for textmate bundles
    - command: mackup backup
      stdin: true
      stdout: true
