- defaults:
    link:
      force: true
      create: true
      relink: true
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true

- shell:
  - 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --unattended || true'
- link:
    ~/.zshrc: zsh/zshrc
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.zshenv: zsh/zshenv
    ~/.oh-my-zsh/custom/plugins/alias-tips: zsh/custom/plugins/alias-tips
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: zsh/custom/plugins/zsh-autosuggestions
    ~/.oh-my-zsh/custom/plugins/zsh-completions: zsh/custom/plugins/zsh-completions
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: zsh/custom/plugins/zsh-syntax-highlighting
    ~/.oh-my-zsh/custom/plugins/zsh-vim-mode: zsh/custom/plugins/zsh-vim-mode
    ~/.oh-my-zsh/custom/themes/powerlevel10k: zsh/custom/themes/powerlevel10k
