- shell:
  - description: oh-my-zsh
    command: '[ -v ZSH ] || sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --unattended'
    stdout: true
    stdin: true
- link:
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/custom: zsh/custom
    
- shell:
  - description: rebuild zcompdump, see https://github.com/zsh-users/zsh-completions#manual-installation
    command: rm -f ~/.zcompdump; compinit
