- shell:
  - description: oh-my-zsh
    command: '[ -v ZSH ] || sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --unattended'
    stdout: true
    stdin: true
- link:
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/custom: zsh/custom