- shell:
  - 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --unattended || true'
- create:
  - ~/.oh-my-zsh/custom/
  - ~/.oh-my-zsh/custom/plugins
  - ~/.oh-my-zsh/custom/themes
- link:
    ~/.zshrc:
      force: true
      path: zsh/zshrc
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.zshenv: zsh/zshenv
    ~/.oh-my-zsh/custom/plugins/alias-tips:
      force: true
      path:  zsh/custom/plugins/alias-tips
    ~/.oh-my-zsh/custom/plugins/zsh-completions:
      force: true
      path:  zsh/custom/plugins/zsh-completions
    ~/.oh-my-zsh/custom/plugins/zsh-vim-mode:
      force: true
      path:  zsh/custom/plugins/zsh-vim-mode
    ~/.oh-my-zsh/custom/themes/powerlevel10k:
      force: true
      path:  zsh/custom/themes/powerlevel10k
