- link:
    ~/.tmux.conf:
      force: true
      path: tmux/tmux.conf
    ~/.tmux/plugins/tpm:
      force: true
      path:  tmux/plugins/tpm
- shell:
        - sh -c "~/.tmux/plugins/tpm/scripts/install_plugins.sh"
