- shell:
  - '[[ $(grep -q docker /etc/group) ]] || sudo groupadd docker'
  - command: '[[ $((groups `whoami`) |grep "\bdocker\b") ]] || ( sudo gpasswd -a `whoami` docker )'
    quiet: false
    stdout: true
    stdin: true
  - '[[ -f "/etc/docker/daemon.json" ]] || (sudo mkdir /etc/docker && sudo cp ~/.dotfiles/etc-docker-daemon.json /etc/docker/daemon.json)'
