- link:
    ~/.vimrc:
        path:  vim/vimrc-glinux
        force: true
    ~/.vim/bundle/Vundle.vim:
        path:  vim/bundle/Vundle.vim
        force: true
- shell:
   - 'vim +PluginInstall +qall'

