- defaults:
    link:
      force: true
      create: true
      relink: true


- link:
    ~/.vimrc: vim/vimrc-glinux
    ~/.vim/bundle/bbye: vim/bundle/bbye
    ~/.vim/bundle/Vundle.vim: vim/bundle/Vundle.vim
- shell:
   - 'vim +PluginInstall +qall'
