- shell:
  - command: 'zsh -c "[ -n \"$ZSH_VERSION\" ] || chsh -s $(which zsh)"'
    description: Making zsh the default shell
    stdin: true
    stdout: true
    quiet: false

- link:
    ~/.zshrc: zsh/zshrc
