- shell:
  - [prodaccess, Getting LOAS credentials]
  - command: '[[ -n $(ganpati2 user show --id=$USER.corp | grep zsh) ]] || ganpati2 user edit --id=$USER.corp --corp_shell=`which zsh` --approve_now=true'
    description: Changing shell

- link:
    ~/.zshrc: zsh/zshrc