- shell:
  - command: '[ -n \"$ZSH_VERSION\" ] || chsh -s $(which zsh)'
    description: Making zsh the default shell
    stdin: true
    stdout: true
    quiet: false

- link:
    ~/.zshrc:
      force: true
      path: zsh/zshrc
