- defaults:
    link:
      force: true
      create: true
      relink: true
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true
- clean: ['~', "~/.ssh/", "~/.vim/", "~/.zshrc-imports/", "~/.zshrc-imports/plugins/"]
- create:
    - ~/.zshrc-imports
    - ~/.zshrc-imports/plugins
    - ~/.tmux
    - ~/.tmux/plugins
    - ~/.vim
    - ~/.vim/bundle
