- defaults:
    link:
      force: true
      create: true
      relink: true
- clean: ['~', "~/.ssh/", "~/.vim/", "~/.zshrc-imports/", "~/.zshrc-imports/plugins/"]
- create:
    - ~/.zshrc-imports
    - ~/.zshrc-imports/plugins
    - ~/.tmux
    - ~/.tmux/plugins
    - ~/.vim
    - ~/.vim/bundle
