- link:
    ~/.zshrc-imports/.zshrc-linux-personal: zsh/zshrc-imports/zshrc-linux-personal
    ~/.zshrc-imports/.aliases-linux-personal: zsh/zshrc-imports/aliases-linux-personal
    ~/.zshrc-imports/plugins/.linux-personal: zsh/zshrc-imports/plugins/linux-personal
