- defaults:
    link:
      force: true
      create: true
      relink: true

- link:
    ~/.zshrc-imports/.zshrc-mac-personal: zsh/zshrc-imports/zshrc-mac-personal
    ~/.zshrc-imports/.aliases-mac-personal: zsh/zshrc-imports/aliases-mac-personal
    ~/.zshrc-imports/plugins/.mac-personal: zsh/zshrc-imports/plugins/mac-personal
