- defaults:
    link:
      force: true
      create: true
      relink: true

- link:
    ~/.zshrc-imports/.zshrc-mac: zsh/zshrc-imports/zshrc-mac
    ~/.zshrc-imports/.aliases-mac: zsh/zshrc-imports/aliases-mac
    ~/.zshrc-imports/plugins/.mac: zsh/zshrc-imports/plugins/mac
