version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:beta-v5.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'archer2016'
    volumes:
      - '~/docker/pihole/etc/pihole/:/etc/pihole/'
      - '~/docker/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ~/docker/pihole/var/log/pihole.log` first unless you like errors
      - '~/docker/pihole/var/log/pihole.log:/var/log/pihole.log'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
