# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mac-os-personal:
    runs-on: macos-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Submodules"
        run: git submodule update --init --recursive --remote

      - name: install
        run: ./install-profile --pull --save-config mac-test mac-personal-test

  mac-os-twitter:
    runs-on: macos-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Submodules"
        run: git submodule update --init --recursive --remote

      - name: install
        run: ./install-profile --pull --save-config mac-test mac-twitter

  ubuntu-docker:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Submodules"
        run: git submodule update --init --recursive --remote

      - name: install
        run: ./install-profile --pull --save-config linux linux-personal raspbian-docker docker-home-server

  ubuntu-personal:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Submodules"
        run: git submodule update --init --recursive --remote

      - name: install
        run: ./install-profile --pull --save-config linux linux-personal linux-gui
