# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  config:
    runs-on: macos-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Submodules"
        run: git submodule update --init --recursive --remote

      - name: install
        run: ./install-profile --pull --save-config mac mac-personal
